[global]
error_log = /dev/stderr

[www]
user = user
group = user
listen.owner = user
listen.group = user
listen.mode = 600
listen = /run/php-fpm.sock
pm = ondemand
pm.max_children = 100
pm.process_idle_timeout = 10s;
pm.max_requests = 1000
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
ping.path = /fpm-ping